//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyAutoConfigDebugger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxyAutoConfigDebugger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Auto-Config (PAC) Debugger
        ///
        ///Editor/Debugger for testing Proxy Auto-Config files.
        ///
        ///Version History:
        ///1.0.1.0: Fixed bug with compiling JavaScript in
        ///         the editor.
        ///1.0.0.0: Initial version for release.
        ///
        ///Things to know:
        ///- Always put &apos;var&apos; in front of variable
        ///  definition.
        ///
        ///- You can use the internal command, 
        ///  __logMessages() to display debugging
        ///  statements. Of course, 
        ///  these are not valid in actual PAC files
        ///  and should be removed prior to use.
        ///
        ///  Example:
        ///    var s=&apos;Thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked_16x {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked_16x {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkmark_16x {
            get {
                object obj = ResourceManager.GetObject("Checkmark_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CSTest_16x {
            get {
                object obj = ResourceManager.GetObject("CSTest_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LordChariot_512x1024 {
            get {
                object obj = ResourceManager.GetObject("LordChariot_512x1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var arguments;
        /////----mine
        ///function FindProxyForURL(host, url) { }
        ///function FindProxyForURLEx(host, url) { }
        ///function __FindProxyForURL(host, url) {
        ///    __clearMessages();
        ///    __logMessage(&apos;&lt;b&gt;FindProxyForURL(&apos; + host + &apos;, &apos; + url + &apos;):&lt;/b&gt;&lt;br/&gt;Starting...\n&apos;);
        ///    var startTime = new Date();
        ///    try {
        ///        var result = FindProxyForURL(host, url);
        ///        document.getElementById(&quot;result&quot;).innerHTML = &apos;&lt;b&gt;&apos; + result + &apos;&lt;/b&gt;&apos;;
        ///        __logMessage(&apos;Return: &lt;b&gt;&apos; + result + &apos;&lt;/b&gt;\r\n&apos;);
        ///        __ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PAC_Functions {
            get {
                return ResourceManager.GetString("PAC_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial,Helvetica,sans-serif;
        ///            font-size: .8em;
        ///        }
        ///        pre {
        ///            font-family: Consolas, &quot;Lucida Console&quot;, Monaco, monospace;
        ///        }
        ///    &lt;/style&gt;
        ///
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        //PAC Functions
        ///        ${P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PAC_Html {
            get {
                return ResourceManager.GetString("PAC_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function FindProxyForURL(url, host) {
        ///
        ///    if (isPlainHostName(host))
        ///        return &quot;DIRECT&quot;;
        ///
        ///    if (
        ///        dnsDomainIs(host, &apos;domain.com&apos;) ||
        ///        shExpMatch(host, &apos;*.domain.com&apos;)
        ///    )
        ///        return &quot;DIRECT&quot;;
        ///
        ///    if (url.substring(0, 4) == &quot;ftp:&quot;)
        ///        return &quot;DIRECT&quot;;
        ///
        ///    if (
        ///        isInNet(host, &quot;127.0.0.0&quot;, &quot;255.0.0.0&quot;) ||
        ///        isInNet(host, &quot;10.0.0.0&quot;, &quot;255.0.0.0&quot;) ||
        ///        isInNet(host, &quot;172.16.0.0&quot;, &quot;255.240.0.0&quot;) ||
        ///        isInNet(host, &quot;192.168.0.0&quot;, &quot;255.25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PAC_JavaScript {
            get {
                return ResourceManager.GetString("PAC_JavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paragraph_16x {
            get {
                object obj = ResourceManager.GetObject("Paragraph_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProxyAutoConfigDebugger {
            get {
                object obj = ResourceManager.GetObject("ProxyAutoConfigDebugger", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_16x {
            get {
                object obj = ResourceManager.GetObject("Save_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search_16x {
            get {
                object obj = ResourceManager.GetObject("Search_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_16x {
            get {
                object obj = ResourceManager.GetObject("Settings_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StyleSheet_16x {
            get {
                object obj = ResourceManager.GetObject("StyleSheet_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextFile_16x {
            get {
                object obj = ResourceManager.GetObject("TextFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIAboutBox_16x {
            get {
                object obj = ResourceManager.GetObject("UIAboutBox_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
